branches:
  only:
   - master
  
before_build:
 - nuget restore Source/NETworkManager.sln
 
image: Visual Studio 2017

configuration: Release

platform: Any CPU

pull_requests:
  do_not_increment_build_number: false

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
