
  
before_build:
 - nuget restore Source/NETworkManager.sln
build_script: 
  - msbuild /t:rebuild "./source/NETworkManager/NETworkManager.csproj" /p:SourceLinkCreate=true /v:n
image: Visual Studio 2017

configuration: Release

platform: Any CPU

pull_requests:
  do_not_increment_build_number: false
